## Import Libraries

In [2]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv("Mental-Health-Twitter.csv")

In [4]:
df.head()

,Unnamed: 0,post_id,post_created,post_text,user_id,followers,friends,favourites,statuses,retweets,label
0,0,637894677824413696,Sun Aug 30 07:48:37 +0000 2015,It's just over 2 years since I was diagnosed w...,1013187241,84,211,251,837,0,1
1,1,637890384576778240,Sun Aug 30 07:31:33 +0000 2015,"It's Sunday, I need a break, so I'm planning t...",1013187241,84,211,251,837,1,1
2,2,637749345908051968,Sat Aug 29 22:11:07 +0000 2015,Awake but tired. I need to sleep but my brain ...,1013187241,84,211,251,837,0,1
3,3,637696421077123073,Sat Aug 29 18:40:49 +0000 2015,RT @SewHQ: #Retro bears make perfect gifts and...,1013187241,84,211,251,837,2,1
4,4,637696327485366272,Sat Aug 29 18:40:26 +0000 2015,It’s hard to say whether packing lists are mak...,1013187241,84,211,251,837,1,1

In [5]:
df.isnull().sum()

Unnamed: 0      0
post_id         0
post_created    0
post_text       0
user_id         0
followers       0
friends         0
favourites      0
statuses        0
retweets        0
label           0
dtype: int64

In [6]:
df= df.drop(columns=['Unnamed: 0'])

In [7]:
df.shape

(20000, 10)

In [8]:
df.duplicated().sum()

np.int64(117)

In [9]:
df['post_id'].duplicated().sum()

np.int64(119)

In [10]:
duplicate_posts = df[df["post_id"].duplicated(keep=False)].sort_values("post_id")

duplicate_posts

,post_id,post_created,post_text,user_id,followers,friends,favourites,statuses,retweets,label
7064,3603064342,Fri Aug 28 14:08:23 +0000 2009,Do Writers Of A T. v Show Use Research Or Prof...,60868031,1768,532,3,5720,0,1
7065,3603064342,Fri Aug 28 14:08:23 +0000 2009,Do Writers Of A T. v Show Use Research Or Prof...,60868031,1768,532,3,5720,0,1
6919,3636366227,Sun Aug 30 01:27:15 +0000 2009,Multiphasic OCs spark menstrual migraines. htt...,60868031,1768,532,3,5720,0,1
6920,3636366227,Sun Aug 30 01:27:15 +0000 2009,Multiphasic OCs spark menstrual migraines. htt...,60868031,1768,532,3,5720,0,1
6775,3663913024,Mon Aug 31 11:37:42 +0000 2009,"A doctor discusses headaches: Causes, cures ht...",60868031,1768,532,3,5720,0,1
...,...,...,...,...,...,...,...,...,...,...
16927,819102472023187456,Wed Jan 11 08:43:42 +0000 2017,RT @wheng71507858: bc bchan ang mga team abroa...,763182466098233344,3088,299,7979,19472,23,0
19937,819356367295311873,Thu Jan 12 01:32:35 +0000 2017,"The lunatic, the lover, and the poet, Are of i...",1169875706,442,230,7,1063601,0,0
19936,819356367295311873,Thu Jan 12 01:32:35 +0000 2017,"The lunatic, the lover, and the poet, Are of i...",1169875706,442,230,7,1063601,0,0
19788,819407379729158145,Thu Jan 12 04:55:17 +0000 2017,"""That must be wonderful! I don't understand it...",1169875706,442,230,7,1063601,0,0
19787,819407379729158145,Thu Jan 12 04:55:17 +0000 2017,"""That must be wonderful! I don't understand it...",1169875706,442,230,7,1063601,0,0

In [11]:
df[df.duplicated(keep=False)]

,post_id,post_created,post_text,user_id,followers,friends,favourites,statuses,retweets,label
141,631531032924303360,Wed Aug 12 18:21:46 +0000 2015,RT @richardbranson: Read this wonderful blog a...,1013187241,84,211,251,837,469,1
142,631531032924303360,Wed Aug 12 18:21:46 +0000 2015,RT @richardbranson: Read this wonderful blog a...,1013187241,84,211,251,837,469,1
392,659337651514945537,Wed Oct 28 11:55:20 +0000 2015,College minor in substance abuse? #addiction h...,3346224328,189,169,698,3694,0,1
393,659337651514945537,Wed Oct 28 11:55:20 +0000 2015,College minor in substance abuse? #addiction h...,3346224328,189,169,698,3694,0,1
537,655952866184679424,Mon Oct 19 03:45:24 +0000 2015,What would your life be like with less #anxiety?,3346224328,189,169,698,3694,1,1
...,...,...,...,...,...,...,...,...,...,...
19599,810367005513498626,Sun Dec 18 06:12:04 +0000 2016,Next Level Fitness https://t.co/cgEVdB5MIT,1458225506,1197,701,1156,61856,0,0
19787,819407379729158145,Thu Jan 12 04:55:17 +0000 2017,"""That must be wonderful! I don't understand it...",1169875706,442,230,7,1063601,0,0
19788,819407379729158145,Thu Jan 12 04:55:17 +0000 2017,"""That must be wonderful! I don't understand it...",1169875706,442,230,7,1063601,0,0
19936,819356367295311873,Thu Jan 12 01:32:35 +0000 2017,"The lunatic, the lover, and the poet, Are of i...",1169875706,442,230,7,1063601,0,0
19937,819356367295311873,Thu Jan 12 01:32:35 +0000 2017,"The lunatic, the lover, and the poet, Are of i...",1169875706,442,230,7,1063601,0,0

In [12]:
df = df.drop_duplicates()

In [13]:
df['post_text'].duplicated().sum()

np.int64(395)

In [15]:
print("Total rows:", len(df))
print("Unique post IDs:", df["post_id"].nunique())
print("Unique users:", df["user_id"].nunique())
print("Exact duplicate rows:", df.duplicated().sum())
print("Duplicated post IDs:", df["post_id"].duplicated().sum())
print("Duplicated texts:", df["post_text"].duplicated().sum())

Total rows: 19883
Unique post IDs: 19881
Unique users: 72
Exact duplicate rows: 0
Duplicated post IDs: 2
Duplicated texts: 395

In [16]:
df = df.drop_duplicates(subset=["post_id"], keep="first").copy()

In [19]:
print("Rows after removing dupliacte post IDs:", len(df))
print("Unique post IDs:", df["post_id"].nunique())
print("Dupliacte post IDs:", df["post_id"].duplicated().sum())

Rows after removing dupliacte post IDs: 19881
Unique post IDs: 19881
Dupliacte post IDs: 0

In [21]:
df["post_text"] = df["post_text"].fillna("").astype(str)

In [22]:
df["post_created"] = pd.to_datetime(
    df["post_created"],
    errors="coerce"
)

In [24]:
print("Final shape:", df.shape)
print("Missing values:", df.isnull().sum().sum())
print("Duplicate post IDs:", df["post_id"].duplicated().sum())
print("Duplicate complete rows:", df.duplicated().sum())

Final shape: (19881, 10)
Missing values: 0
Duplicate post IDs: 0
Duplicate complete rows: 0

In [25]:
df[["post_text"]].head(10)

                                           post_text
0  It's just over 2 years since I was diagnosed w...
1  It's Sunday, I need a break, so I'm planning t...
2  Awake but tired. I need to sleep but my brain ...
3  RT @SewHQ: #Retro bears make perfect gifts and...
4  It’s hard to say whether packing lists are mak...
5  Making packing lists is my new hobby... #movin...
6  At what point does keeping stuff for nostalgic...
7  Currently in the finding-boxes-of-random-shit ...
8  Can't be bothered to cook, take away on the wa...
9  RT @itventsnews: ITV releases promo video for ...

In [26]:
df["text_clean"]= df["post_text"].copy()

In [52]:
import re
def clean_text(text):
    text = str(text).lower()
    text = text.replace("'","'")
    text = re.sub(r'\brt\b','',text)
    text = re.sub(r'http\S+|www\S+','',text)
    text = re.sub(r'@\w+','',text)
    text = text.replace('#','')
    text = re.sub(r"[^\w\s']",' ',text)
    text = re.sub(r'\s+',' ',text)
    text = text.strip()
    return text

In [53]:
df["text_clean"] = df["post_text"].apply(clean_text)

In [54]:
df[["post_text","text_clean"]].head(10)

,post_text,text_clean
0,It's just over 2 years since I was diagnosed w...,it's just over 2 years since i was diagnosed w...
1,"It's Sunday, I need a break, so I'm planning t...",it's sunday i need a break so i'm planning to ...
2,Awake but tired. I need to sleep but my brain ...,awake but tired i need to sleep but my brain h...
3,RT @SewHQ: #Retro bears make perfect gifts and...,retro bears make perfect gifts and are great f...
4,It’s hard to say whether packing lists are mak...,it s hard to say whether packing lists are mak...
5,Making packing lists is my new hobby... #movin...,making packing lists is my new hobby movinghouse
6,At what point does keeping stuff for nostalgic...,at what point does keeping stuff for nostalgic...
7,Currently in the finding-boxes-of-random-shit ...,currently in the finding boxes of random shit ...
8,"Can't be bothered to cook, take away on the wa...",can't be bothered to cook take away on the way...
9,RT @itventsnews: ITV releases promo video for ...,itv releases promo video for the final series ...

In [55]:
print(df["text_clean"].head(10).to_string(index=False))

it's just over 2 years since i was diagnosed wi...
it's sunday i need a break so i'm planning to s...
awake but tired i need to sleep but my brain ha...
retro bears make perfect gifts and are great fo...
it s hard to say whether packing lists are maki...
  making packing lists is my new hobby movinghouse
at what point does keeping stuff for nostalgic ...
currently in the finding boxes of random shit p...
can't be bothered to cook take away on the way ...
itv releases promo video for the final series o...

In [56]:
empty_text = (df["text_clean"].str.strip() == "").sum()
print("Empty cleaned tweets:", empty_text)

Empty cleaned tweets: 0

In [57]:
print(df.shape)
print(df[["post_text","text_clean"]].head())

(19881, 11)
                                           post_text  \
0  It's just over 2 years since I was diagnosed w...
1  It's Sunday, I need a break, so I'm planning t...
2  Awake but tired. I need to sleep but my brain ...
3  RT @SewHQ: #Retro bears make perfect gifts and...
4  It’s hard to say whether packing lists are mak...

                                          text_clean
0  it's just over 2 years since i was diagnosed w...
1  it's sunday i need a break so i'm planning to ...
2  awake but tired i need to sleep but my brain h...
3  retro bears make perfect gifts and are great f...
4  it s hard to say whether packing lists are mak...

In [59]:
print("Rows:", len(df))
print("Columns:", len(df.columns))
print("Empty cleaned tweets:", (df["text_clean"] == "").sum())

Rows: 19881
Columns: 11
Empty cleaned tweets: 0

In [60]:
df["word_count"] = df["post_text"].str.split().str.len()

In [61]:
df["char_count"] = df["post_text"].str.len()

In [62]:
df["hashtag_count"] = df["post_text"].str.count(r"#\w+")

In [63]:
df["mention_count"] = df["post_text"].str.count(r"@\w+")

In [64]:
df["url_count"] = df["post_text"].str.count(
    r"http\S+|www\S+"
)

In [65]:
df["question_count"] = df["post_text"].str.count(r"\?")

In [66]:
df["exclamation_count"] = df["post_text"].str.count(r"!")

In [67]:
df["uppercase_count"] = df["post_text"].apply(
    lambda x:sum(1 for c in str(x) if c.isupper())
)

In [68]:
feature_columns = [
    "word_count",
    "char_count",
    "hashtag_count",
    "mention_count",
    "url_count",
    "question_count",
    "exclamation_count",
    "uppercase_count"
]
df[feature_columns].head(10)

,word_count,char_count,hashtag_count,mention_count,url_count,question_count,exclamation_count,uppercase_count
0,26,140,2,0,0,0,0,5
1,19,95,1,0,0,0,0,5
2,13,64,0,0,0,0,0,2
3,23,140,2,1,1,0,2,12
4,21,133,2,0,0,0,0,1
5,8,52,1,0,0,0,0,1
6,17,110,1,0,0,1,0,1
7,12,92,0,0,0,0,0,3
8,12,57,1,0,0,0,0,1
9,15,125,0,1,2,0,0,17

In [69]:
df[feature_columns].describe()

,word_count,char_count,hashtag_count,mention_count,url_count,question_count,exclamation_count,uppercase_count
count,19881.000000,19881.000000,19881.000000,19881.000000,19881.000000,19881.000000,19881.00000,19881.000000
mean,12.530255,82.509079,0.178814,0.670691,0.455208,0.170665,0.36975,8.884211
std,6.859315,38.280887,0.561388,0.926716,0.549390,0.618622,1.45224,10.813843
min,1.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
25%,7.000000,50.000000,0.000000,0.000000,0.000000,0.000000,0.00000,3.000000
50%,12.000000,77.000000,0.000000,0.000000,0.000000,0.000000,0.00000,6.000000
75%,18.000000,118.000000,0.000000,1.000000,1.000000,0.000000,0.00000,11.000000
max,34.000000,169.000000,8.000000,9.000000,3.000000,19.000000,57.00000,115.000000

In [70]:
df.groupby("label")[feature_columns].mean()

,word_count,char_count,hashtag_count,mention_count,url_count,question_count,exclamation_count,uppercase_count
label,,,,,,,,
0,12.233625,81.978871,0.112486,0.677634,0.473790,0.152732,0.533756,9.852400
1,12.826795,83.039127,0.245122,0.663750,0.436632,0.188594,0.205794,7.916315

In [71]:
df[feature_columns].head(10)

,word_count,char_count,hashtag_count,mention_count,url_count,question_count,exclamation_count,uppercase_count
0,26,140,2,0,0,0,0,5
1,19,95,1,0,0,0,0,5
2,13,64,0,0,0,0,0,2
3,23,140,2,1,1,0,2,12
4,21,133,2,0,0,0,0,1
5,8,52,1,0,0,0,0,1
6,17,110,1,0,0,1,0,1
7,12,92,0,0,0,0,0,3
8,12,57,1,0,0,0,0,1
9,15,125,0,1,2,0,0,17

## Sentiment Analysis

In [72]:
!pip install vaderSentiment

Collecting vaderSentiment
  Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl.metadata (572 bytes)
Requirement already satisfied: requests in C:\Users\lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages (from vaderSentiment) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in C:\Users\lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->vaderSentiment) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->vaderSentiment) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->vaderSentiment) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->vaderSentiment) (2025.4.26)
Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl (125 kB)
Installing collected packages: vaderSentiment
Successfully installed vaderSentiment-3.3.2

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [74]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()

In [75]:
text = df["post_text"].iloc[0]
scores = analyzer.polarity_scores(text)
print(text)
print(scores)

It's just over 2 years since I was diagnosed with #anxiety and #depression. Today I'm taking a moment to reflect on how far I've come since.
{'neg': 0.184, 'neu': 0.816, 'pos': 0.0, 'compound': -0.6597}

In [76]:
df["sentiment_score"] = df["post_text"].apply(
    lambda x: analyzer.polarity_scores(x)["compound"]
)
def sentiment_category(score):
    if score >= 0.05:
        return "Positive"
    elif score <= -0.05:
        return "Negative"
    else:
        return "Neutral"
df["sentiment"] = df["sentiment_score"].apply(sentiment_category)

In [77]:
df["sentiment"].value_counts()

sentiment
Positive    7650
Neutral     6748
Negative    5483
Name: count, dtype: int64

In [79]:
df["sentiment"].value_counts(normalize=True).mul(100).round(2)

sentiment
Positive    38.48
Neutral     33.94
Negative    27.58
Name: proportion, dtype: float64

In [82]:
pd.crosstab(
    df["label"],
    df["sentiment"],
    normalize="index"
).mul(100).round(2)

sentiment  Negative  Neutral  Positive
label
0             23.80    38.56     37.65
1             31.36    29.33     39.31

In [84]:
df.groupby("label")["sentiment_score"].agg(
    ["mean","median","std","min","max"]
).round(3)

        mean  median    std    min    max
label
0      0.082     0.0  0.433 -0.989  0.996
1      0.056     0.0  0.477 -0.981  0.999

In [85]:
df.groupby("sentiment")["sentiment_score"].agg(
    ["mean","min","max"]
).round(3)

            mean    min    max
sentiment
Negative  -0.499 -0.989 -0.050
Neutral    0.000 -0.050  0.050
Positive   0.536  0.052  0.999

In [86]:
df["post_created"].dtype

datetime64[ns, UTC]

In [88]:
df["post_created"] = pd.to_datetime(
    df["post_created"],
    errors="coerce"
)

In [89]:
df["post_created"].isna().sum()

np.int64(0)

In [92]:
df["date"] = df["post_created"].dt.date
df["year"] = df["post_created"].dt.year
df["month"] = df["post_created"].dt.month

In [93]:
df[["post_created","date","year","month"]].head()

               post_created        date  year  month
0 2015-08-30 07:48:37+00:00  2015-08-30  2015      8
1 2015-08-30 07:31:33+00:00  2015-08-30  2015      8
2 2015-08-29 22:11:07+00:00  2015-08-29  2015      8
3 2015-08-29 18:40:49+00:00  2015-08-29  2015      8
4 2015-08-29 18:40:26+00:00  2015-08-29  2015      8

In [94]:
print("Start date:", df["post_created"].min())
print("End date:", df["post_created"].max())

Start date: 2009-08-26 13:19:08+00:00
End date: 2017-01-12 08:13:53+00:00

In [95]:
df["year_month"] = df["post_created"].dt.to_period("M")

In [96]:
monthly_posts = (
    df.groupby("year_month")
    .size()
    .reset_index(name="post_count")
)
monthly_posts.head()

  year_month  post_count
0    2009-08         420
1    2009-09         107
2    2010-11           2
3    2012-09           1
4    2012-12         135

In [97]:
monthly_label = (
    df.groupby(["year_month","label"])
    .size()
    .reset_index(name="post_created")
)
monthly_label.head()

  year_month  label  post_created
0    2009-08      1           420
1    2009-09      1           107
2    2010-11      1             2
3    2012-09      1             1
4    2012-12      1           135

In [98]:
monthly_sentiment = (
    df.groupby(["year_month","label"])["sentiment_score"]
    .mean()
    .reset_index()
)
monthly_sentiment.head(10)

  year_month  label  sentiment_score
0    2009-08      1        -0.032457
1    2009-09      1        -0.025122
2    2010-11      1         0.322350
3    2012-09      1        -0.365300
4    2012-12      1         0.090306
5    2013-01      1        -0.065570
6    2013-02      1         0.344702
7    2013-04      1         0.273627
8    2013-05      1        -0.340700
9    2013-12      1         0.176489

In [99]:
yearly_posts = (
    df.groupby(["year","label"])
    .size()
    .reset_index(name="posted_count")
)
yearly_posts

   year  label  posted_count
0  2009      1           527
1  2010      1             2
2  2012      1           136
3  2013      1           426
4  2014      1          1287
5  2015      1          7056
6  2016      0          4992
7  2016      1           508
8  2017      0          4947

In [100]:
yearly_sentiment = (
    df.groupby(["year","label"])["sentiment_score"]
    .mean()
    .reset_index()
)
yearly_sentiment

   year  label  sentiment_score
0  2009      1        -0.030968
1  2010      1         0.322350
2  2012      1         0.086956
3  2013      1         0.109229
4  2014      1         0.047863
5  2015      1         0.059733
6  2016      0         0.084790
7  2016      1         0.052410
8  2017      0         0.079097

In [101]:
df["year"].value_counts().sort_index()

year
2009     527
2010       2
2012     136
2013     426
2014    1287
2015    7056
2016    5500
2017    4947
Name: count, dtype: int64

In [103]:
sentiment_by_label = (
    df.groupby("label")["sentiment_score"]
    .agg(["mean","median","std","count"])
    .round(3)
)
sentiment_by_label

        mean  median    std  count
label
0      0.082     0.0  0.433   9939
1      0.056     0.0  0.477   9942

In [104]:
negative_by_label =(
    pd.crosstab(
        df["label"],
        df["sentiment"],
        normalize="index"
    )*100
).round(2)
negative_by_label

sentiment  Negative  Neutral  Positive
label
0             23.80    38.56     37.65
1             31.36    29.33     39.31

In [106]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [107]:
tfidf = TfidfVectorizer(
    max_features=5000,
    min_df=5,
    max_df=0.95,
    stop_words="english"
)

In [108]:
X_tfidf = tfidf.fit_transform(df["text_clean"])

In [109]:
print("TF-IDF shape:", X_tfidf.shape)

TF-IDF shape: (19881, 3810)

In [110]:
feature_names = tfidf.get_feature_names_out()
print(feature_names[:50])

['00' '000' '03' '10' '100' '1000' '100th' '101' '10k' '11' '12' '13' '14'
 '15' '16' '17' '18' '19' '1d' '1st' '20' '200' '2000' '2011' '2012'
 '2013' '2014' '2015' '2016' '2017' '21' '21st' '22' '23' '24'
 '24detailsofzayn' '25' '26' '27' '28' '29' '2k' '30' '300' '30am' '30s'
 '35' '37' '39' '3rd']

In [113]:
tfidf_df = pd.DataFrame(
    X_tfidf.toarray(),
    columns=feature_names,
    index=df.index
)
label_tfidf = tfidf_df.groupby(df["label"]).mean()
term_difference = label_tfidf.loc[1] - label_tfidf.loc[0]
top_label_1 = term_difference.sort_values(ascending=False).head(20)
top_label_0 = term_difference.sort_values().head(20)

print("Top terms associated with Label 1:")
print(top_label_1)

print("\nTop terms associated with Label 0:")
print(top_label_0)

Top terms associated with Label 1:
depression    0.023170
treatments    0.008893
overcome      0.007056
talk          0.006423
health        0.005256
mental        0.004795
help          0.004725
migraine      0.004503
today         0.004269
anxiety       0.004161
addiction     0.003887
migraines     0.003759
day           0.003716
business      0.003630
lt            0.003531
life          0.003273
autism        0.003232
treatment     0.003188
make          0.003150
headaches     0.003138
dtype: float64

Top terms associated with Label 0:
user              -0.048161
yong              -0.011248
trump             -0.011084
thank             -0.007219
following         -0.006592
twitter           -0.006376
hello             -0.006339
say               -0.006223
hey               -0.006101
wearepayting      -0.005204
foryong           -0.005188
putin             -0.005033
thanks            -0.004847
zayn              -0.004734
aleph             -0.004534
paytforluckysun   -0.004350
bestmusicvideo    -0.004298
pillowtalk        -0.004252
anytime           -0.004252
iheartawards      -0.004206
dtype: float64

In [114]:
df[[
    "followers",
    "friends",
    "favourites",
    "statuses",
    "retweets"
]].describe().round(2)

       followers   friends  favourites    statuses   retweets
count   19881.00  19881.00    19881.00    19881.00   19881.00
mean      900.87    783.35     6397.89    44382.73    1442.82
std      1904.63   1839.77     8394.49   140805.41   15161.30
min         0.00      0.00        0.00        3.00       0.00
25%       177.00    211.00      243.00     5129.00       0.00
50%       476.00    561.00     2752.00    13251.00       0.00
75%      1197.00    701.00     8229.00    52892.00       1.00
max     28614.00  28514.00    39008.00  1063601.00  839540.00

In [115]:
df.groupby("label")[[
    "followers",
    "friends",
    "favourites",
    "statuses",
    "retweets"
]].mean().round(2)

       followers  friends  favourites  statuses  retweets
label
0         920.81   562.60     8513.59  79077.38   1826.81
1         880.94  1004.03     4282.84   9698.55   1058.94

In [116]:
final_df = df[
    [
        "post_id",
        "post_created",
        "post_text",
        "text_clean",
        "label",
        "sentiment_score",
        "sentiment",
        "word_count",
        "char_count",
        "hashtag_count",
        "mention_count",
        "url_count",
        "question_count",
        "exclamation_count",
        "uppercase_count",
        "year",
        "month"
    ]
].copy()

print(final_df.shape)
final_df.head()

(19881, 17)

,post_id,post_created,post_text,text_clean,label,sentiment_score,sentiment,word_count,char_count,hashtag_count,mention_count,url_count,question_count,exclamation_count,uppercase_count,year,month
0,637894677824413696,2015-08-30 07:48:37+00:00,It's just over 2 years since I was diagnosed w...,it's just over 2 years since i was diagnosed w...,1,-0.6597,Negative,26,140,2,0,0,0,0,5,2015,8
1,637890384576778240,2015-08-30 07:31:33+00:00,"It's Sunday, I need a break, so I'm planning t...",it's sunday i need a break so i'm planning to ...,1,0.0000,Neutral,19,95,1,0,0,0,0,5,2015,8
2,637749345908051968,2015-08-29 22:11:07+00:00,Awake but tired. I need to sleep but my brain ...,awake but tired i need to sleep but my brain h...,1,-0.5927,Negative,13,64,0,0,0,0,0,2,2015,8
3,637696421077123073,2015-08-29 18:40:49+00:00,RT @SewHQ: #Retro bears make perfect gifts and...,retro bears make perfect gifts and are great f...,1,0.9150,Positive,23,140,2,1,1,0,2,12,2015,8
4,637696327485366272,2015-08-29 18:40:26+00:00,It’s hard to say whether packing lists are mak...,it s hard to say whether packing lists are mak...,1,0.1779,Positive,21,133,2,0,0,0,0,1,2015,8

In [117]:
final_df.to_csv("Mental_Health_Sentiment_Final.csv", index=False)